### ISSUE TITLE
Grid with a width of 100% renders incorrectly

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#2494]
### Description  
A grid with a width of 100% renders incorrectly

 * igniteui-angular version: 6.1.4
 * browser: Chrome 68.0.3440.106

### Steps to reproduce  

1. Open sample [Live example](https://angular-mwzuvp.stackblitz.io/)
2. Delete cache and reload

### Result  
The grid is rendered incorrectly

### Expected result  
The grid is rendered correctly

I think the issue is happening with the calculation of calcWidth. When you resize the window the issue is fixed, The width in that line is '100%' so the computed value is 100.

https://github.com/IgniteUI/igniteui-angular/blob/2b4de7324fbec2e10d1d6602b32fb11157eeab69/projects/igniteui-angular/src/lib/grid/grid.component.ts#L3330

### Attachments  
[Example](https://stackblitz.com/edit/angular-mwzuvp)
![image](https://user-images.githubusercontent.com/7459881/44609599-f40dc200-a7bd-11e8-8fa9-a702b43321e2.png)
[angular-mwzuvp.zip](https://github.com/IgniteUI/igniteui-angular/files/2320000/angular-mwzuvp.zip)

**Comment by kdinev** [comment]
@lalo-mx By default, if you don't set any `width` to the grid, it would be sized at `100%` and it wouldn't go through the sizing computation. Try removing the `width` from the container as a temporary fix.

**Comment by zdrawku** [comment]
Let us know if you have more questions, closing the issue for now.

**Comment by lalo-mx** [comment]
Was the bug fixed?

**Comment by kdinev** [comment]
I think this was closed by mistake. Reopening.

**Comment by zdrawku** [comment]
Yes, my mistake, @lalo-mx tommorow I will give you more detailed status of this issue.

**Comment by Eralmidia** [comment]
@kdinev @zdrawku  Whats the status on this for 6.2? Is it influenced by #2384 ? We have also had issues with the grid width. Also, any chance any of this could impact #1995 positively?

**Comment by zdrawku** [comment]
@Eralmidia and @lalo-mx there is a [issue](https://github.com/IgniteUI/igniteui-angular/issues/1861) that describes the problem that @lalo-mx experienced, it is related to the height, but applies also to the width percent rendering. As I am familiar @ChronosSF is currently researching a way to render grid sizes based on the visible row data that the end user can set. @ChronosSF can you share more

**Comment by kdinev** [comment]
@zdrawku @Eralmidia The records-based rendering was pushed back and won't make it into 6.2.0. 

@ChronosSF We should fix this issue, since we won't have the records-based rendering, because it's a chore for users right now.

**Comment by ChronosSF** [comment]
Just for clarification width in % is defined as the browser window always has width in pixels to derive % width from. So this does not fall into the same loophole we were trying to resolve with #2384 

This looks like a bug that we should fix, yes.

**Comment by ChronosSF** [comment]
@lalo-mx , are you still able to reproduce the issue with the sample that is linked?

We did have an issue with 100% being used as 100 pixels for calculations but it seems to have been fixed prior to 6.1.4 release.

**Comment by lalo-mx** [comment]
Yes, it looks the sample is working now but i have no idea what changed. Maybe a Chrome related bug or StackBlitz.
In our app the bugs it is still happening but i have not found the difference between the sample and our code.

**Comment by zdrawku** [comment]
All StackBlitz demos are up and running. @lalo-mx could you let us know if the issue still persist after upgrading to [igniteui-angular 6.2.0](https://www.npmjs.com/package/igniteui-angular/v/6.2.0)?

**Comment by SlavUI** [comment]
@lalo-mx  closing this one if there is still an issue please reopen it :)
