### ISSUE TITLE
There is an empty area in the igxGrid after scrolling ungrouping and then grouping again

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#2987]
### Description  
There is an empty area (gap) in the igxGrid after scrolling ungrouping and then grouping again.

 * igniteui-angular version: 6.2.0
 * browser: *

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html#live-updating-demo
2. Scroll down with the mouse wheel
3. Click on the "Grouped" switch
4. Click on the "Grouped" switch again

### Result  
There is an empty area in the grid

### Expected result  
There should be no empty area in the grid and the rows should span the whole view port.

### Attachments  
![image](https://user-images.githubusercontent.com/6794133/48348425-034c2f80-e68a-11e8-8c82-4d5a487f5265.png)

**Comment by skrustev** [comment]
This should be fixed by PR #2984

**Comment by hanastasov** [comment]
Issue is still reproducible on https://www.infragistics.com/angular-demos/finjs-sample
