### ISSUE TITLE
Keyboard Navigation Issues in the Hierarchical Grid

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#4280]
## Description  

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

- [x] Can not navigate to root summary row when press **Tab** over the last cell in the grid's body - should be fixed with https://github.com/IgniteUI/igniteui-angular/pull/4293

- [x] Error is thrown when click over summary cell and press **Tab** or **Shift + Tab** - should be fixed with https://github.com/IgniteUI/igniteui-angular/pull/4293

- [x] When child grid is filterable and the focus is on the last filtering chip of that grid and press **Tab** the error is thrown in the console - should be fixed with https://github.com/IgniteUI/igniteui-angular/pull/4267

## Result  
Errors are thrown in the console and navigation is not performed.

## Expected result  
Should not be thrown errors in the console and the navigation should be performed as expected
## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
@ddincheva 
1) should be resolved with - https://github.com/IgniteUI/igniteui-angular/pull/4221
3) should re resolved with https://github.com/IgniteUI/igniteui-angular/pull/4267

Regarding the summary below each grid, should it be part of the Tab sequence but not part of the Keyboard navigation with arrow keys?

**Comment by ddincheva** [comment]
Yes, the root summaries for the grid can be accessed only with tab, and can return from them to the grid's body with shift  + tab. When we have a summaries on child level (when grouping is applied) the summary cells are part of the grid's body so they can be accessed with arrow keys. :)

**Comment by ddincheva** [comment]
Also the first issue is still reproducible for the child grids in #4221
