### ISSUE TITLE
Filtering to no rows hides the filter dropdown

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#691]
### Description  
Filtering to no rows hides the filter dropdown

### Steps to reproduce  
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
Run the grid sample
Drop down the filter
type in XX

### Result  
![image](https://user-images.githubusercontent.com/19844934/36814062-79b71f46-1ca4-11e8-8792-95b85417a396.png)

With the dropdown hidden, if you close and re-open the filter, you cannot get to the filter condition to change it. 

### Expected result  
Either the grid doesn't completely shrink down, or the DropDown appears outside the bounds of the grid. 

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
This is no longer reproducible with 5.2.0.

![image](https://user-images.githubusercontent.com/1472513/36892716-4ede680e-1e0e-11e8-90c7-9fe29f7afc68.png)

**Comment by zdrawku** [comment]
Hey @MikeTechSpeak apologies for the inconvenience related to the issue, we have fixed it in our igniteui-angular repository 3 days ago, and the changes are not yet pushed to production.

Issue - https://github.com/IgniteUI/igniteui-angular-samples/issues/119
PR with the fix - https://github.com/IgniteUI/igniteui-angular-samples/pull/123/files

Thank you for paying attention to our product and for your help to constantly improve it :)

**Comment by MikeTechSpeak** [comment]
The fix for the issue was to set a height in the sample, but that is a dodge of a fix.  In that if in usage you do not want to have a height, the issue will still happen. While the sample looks correct now, the behavior is still in the grid itself. You can verify that by going here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
View on StackBlitz
Go to the grid\services\grid.component.html
In the igx-grid remove the height property.
Filter the grid to no rows
Either the grid needs a min height property implemented, or the filter dropdown needs to be able to show outside the grid container.

**Comment by zdrawku** [comment]
I agree with you, the fix was sample specific and did not fixed the core hidden dialog issue.

[New issue](https://github.com/IgniteUI/igniteui-angular/issues/940) has been logged because we need to decide which approach is going to be followed.
