### ISSUE TITLE
[igx-grid][ExcelStyleFiltering]Dialog position when scrolling down to the bottom of the page and click the excel style filtering icon.

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-angular#7742]
## Description  
When the scroll bar is appeared in the window and scroll down to the bottom of the page, the dialog is not appropriately shown. If the window is not scrolled, the position is adjusted automatically.

 * igniteui-angular version: 9.1.11
 * browser: chrome 83.0.4103.116

## Steps to reproduce  

1. See [https://stackblitz.com/edit/angular-igniteui-10-popup-position-scroll](https://stackblitz.com/edit/angular-igniteui-10-popup-position-scroll) and scroll down to the bottom of the page.
2. Open the excel style filtering dialog in the 3rd grid.

## Result  
The dialog is not fully shown and will be cut.
![49cb9b658e5936a0d329b7d32c2537b0](https://user-images.githubusercontent.com/5829221/86557405-fc75dd00-bf90-11ea-97a8-a9b39945f5a5.gif)

## Expected result  
The user can see the dialog fully and click the bottom buttons.
<img width="728" alt="b9250a831f739bce9f20ff05dc1f1916" src="https://user-images.githubusercontent.com/5829221/86557418-04ce1800-bf91-11ea-86c9-4abf5741b56f.png">

**Comment by astaev** [comment]
@cleverdog,

This issue is not reproducible with the latest 9.1 and 10.0 versions of igniteui-angular. Having this in mind, updating to latest source should fix the behavior that you are experiencing. 
The version of igniteui-angular that you pointed is 9.1.11 which seems to be incorrect, since the latest available version of 9.1 is 9.1.7. My guess is that you are using a version prior to 9.1, and according to our maintenance and versioning policy we are not supporting versions older that 9.1.

**Comment by cleverdog** [comment]
@astaev 

Thanks for confirming.
I miswrote the version number. Actually it was 9.1.5.

I updated the version to 9.1.7 but the issue looks still persists.
[stackblitz.com/edit/angular-igniteui-10-popup-position-scroll-4atexf](https://stackblitz.com/edit/angular-igniteui-10-popup-position-scroll-4atexf)

Could you check this sample?
