### ISSUE TITLE
Input type textarea is not visualized correctly when used inside input group

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-angular#7776]
## Description  
When using <textarea> in the igx-input-group, becoming line-height to zero by styling.
This issue about only version 10.

Related #7548 

 * igniteui-angular version: 10.0.3
 * browser: Chrome 83.0.4103.116

## Steps to reproduce  

1. See the https://stackblitz.com/edit/igx-inputgroup-textarea-10
2. enter something to the text area.

## Result  
<img src="https://i.gyazo.com/bac56fcbe6de7ea378b7cbef75cd1d50.png" alt="Image from Gyazo" width="307"/>
The text can't be shown fully and are place same line.

## Expected result
<img src="https://i.gyazo.com/6d0a18b9e5716cf387050507b8be2810.png" alt="Image from Gyazo" width="307"/>

https://stackblitz.com/edit/igx-inputgroup-textarea-9
working well for version 9.

**Comment by Lipata** [comment]
Hi, @cleverdog.

There was already such issues #7737 and #7752, which were fixed. You can try [igniteui-angular@10.0.4](https://github.com/IgniteUI/igniteui-angular/releases) (later today) and see if you are experiencing the problem.

**Comment by cleverdog** [comment]
Did the fix marge to 9.1.x?
I made a super simple sample by Ignite UI for angular 9.1.
https://github.com/cleverdog/angular9_textarea
The issue still persists.

**Comment by wnvko** [comment]
There were no PR targeting 9.1.x for this issue. @simeonoff should we fix this in 9.1.x too?

**Comment by simeonoff** [comment]
@wnvko Do we still support 9.1.x releases?

**Comment by radomirchev** [comment]
@simeonoff 9.1.x is still in support. Bug fixing PRs should be targeting against 9.1.x, 10.1.x and master.
