### ISSUE TITLE
IgxHierarchicalGrid - Text in the selected cell is not copied properly.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#9782]
## Description  
Text in the selected cell is not copied properly.
It looks like the cell below the selected cell is copied instead.

 * igniteui-angular version: 12.0.5
 * browser: Chrome

## Steps to reproduce  

1.	Go to the stackblitz sample:
https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos-lob/hierarchical-grid/hierarchical-grid-resizing
2.	Expand the first row.
3.	Scroll down the grid so that the next row is visible.
4.	Click the Artist column cell on the second row ('Babila Ebwélé').
5.	Press Ctrl + C to copy the selected cell to the clipboard.
6.	Press Ctrl + V on a text editor.

## Result  
'Artist
Ahmad Nazeri' is pasted.

## Expected result  
'Artist
Babila Ebwélé' is pasted.

**Comment by radomirchev** [comment]
@mkamiishi , I have followed the steps described by you and cannot reproduce the bug. I receive correct result: "Artist
Babila Ebwélé". Could you confirm the results on your side?

**Comment by mkamiishi** [comment]
@radomirchev 
Yes, this is still reproducible in the stackblitz sample on my side.
[20210705_174727.zip](https://github.com/IgniteUI/igniteui-angular/files/6762981/20210705_174727.zip)

I have recorded my testing.

**Comment by ymita** [comment]
@radomirchev , @dobromirts , @zdrawku 
The customer who reported this issue asks the current status of this issue. Let me ask two questions:
1. Have we already reproduced the symptom that Mihoko described earlier?
2. Is there a workaround for this issue?

Thank you in advance,
Yuki

**Comment by dobromirts** [comment]
Hello @ymita ,
The current status of this issue is in development. We have reproduced this behaviour and we will notify you as soon as the solution is ready or with an appropriate workaround for it.

**Comment by ymita** [comment]
Hi @dobromirts ,
Thank you for your prompt reply. I understand the current status. I am looking forward to the update. Thank you.

**Comment by zdrawku** [comment]
The fix is merged and will be available with the weekly patches on Monday for 10.2.x, 11.1.x and 12.1.x

**Comment by ymita** [comment]
@dobromirts , @zdrawku 

I tested with the latest build(12.1.8) but I see this is still reproducible. Would you take a look at it? The sample is here:: https://codesandbox.io/s/hardcore-flower-701fu

**Comment by dobromirts** [comment]
Hello @ymita , thank you for your reply we are going to take a look at it and will update you as soon as this issue is resolved.
